LOAD DATA INFILE '/data/91jili/merge/script/vote/migrate_vote.csv' 
INTO TABLE vote 
CHARACTER SET UTF8  
FIELDS  TERMINATED BY ','  
OPTIONALLY ENCLOSED BY '"' 
ESCAPED BY '"' LINES 
TERMINATED BY '\r\n';
