
test:
	/usr/local/bin/phpunit -c ./app/ -d memory_limit=-1 -v --debug | tee /tmp/report

assets-rebuild:
	php ./app/console assets:install web --symlink --relative

deploy-js-routing: assets-rebuild
	./app/console	fos:js-routing:dump

fix-perms:
	mkdir -p  app/{cache,logs,sessions,cache_data,logs_data}
	mkdir -p web/images/actionPic
	sudo chgrp -R apache app/cache
	sudo chgrp -R apache app/cache_data
	sudo chgrp -R apache app/logs
	sudo chgrp -R apache web/images/actionPic
	sudo chmod -R g+w  app/cache
	sudo chmod -R g+w  app/cache_data
	sudo chmod -R g+w  app/logs
	sudo chmod -R g+w   web/images/actionPic 
	sudo chgrp -R apache app/sessions 
	sudo chmod -R g+w  app/sessions
	sudo chgrp -R apache app/logs_data 
	sudo chmod -R g+w  app/logs_data

fix-777:
	sudo chgrp -R apache app/cache
	sudo chgrp -R apache app/cache_data
	sudo chgrp -R apache app/logs
	sudo chgrp -R apache web/images/actionPic
	sudo chmod -R 777  app/cache
	sudo chmod -R 777  app/cache_data
	sudo chmod -R 777  app/logs
	sudo chmod -R 777   web/images/actionPic 
	sudo chgrp -R apache app/sessions 
	sudo chmod -R 777  app/sessions
	sudo chgrp -R apache app/logs_data 
	sudo chmod -R 777  app/logs_data

deploy: deploy-js-routing
	@echo done

cc-cache:
	sudo rm -rf app/cache/*

cc-all:
	sudo rm -rf app/cache/*
	sudo rm -rf app/cache_data/*
	sudo rm -rf app/logs/*
	sudo rm -rf app/logs_data/*
	sudo rm -rf app/sessions/*
