<?php
namespace Jili\EmarBundle\Repository;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
use Doctrine\ORM\Query;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * EmarActivityCommissionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmarActivityCommissionRepository extends EntityRepository
{
    public function getCommissionListByMallName($mallName)
    {
        $query = $this->createQueryBuilder('eac');
        $query = $query->select('eac.commissionName,eac.rebateType,eac.rebate');
        $query = $query->Where('eac.mallName = :mallName');
        $query = $query->andWhere('eac.rebate > 0');
        $query = $query->setParameters(array (
            'mallName' => $mallName
        ));
        $query->orderBy('eac.rebateType', 'ASC');
        $query = $query->getQuery();
        return $query->getResult();
    }
}
