imports:
    - { resource: config.yml }

# In production environment you should know that the parameters for URL generation
# always pass the requirements. Otherwise it would break your link (or even site with
# strict_requirements = true). So we can disable the requirements check completely for
# enhanced performance with strict_requirements = null.
framework:
    router:
        strict_requirements: null
    #validation:
    #    cache: apc

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        main:
            type: stream
            path: "%jili_app.logs_dir%/sf2/%kernel.environment%.log"
            level: info
            channels: [!event]

parameters:
# NOTICE: product config use demo one.
    emar_com.app_AppKey: %emar_com.demo.AppKey%
    emar_com.app_AppSecret: %emar_com.demo.AppSecret%

