imports:
    - { resource: config.yml }
    - { resource: secret_staging.yml }

framework:
    router:
        strict_requirements: null

monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: info
            channels: [ !event, !request, !security ]
