imports:
    - { resource: config_dev.yml }

parameters:
    database_host:     192.168.1.235
    database_name:     jili_zhang
    database_password: ecnavi 

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        enabled: false 

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true
    spool:
        type: file
        path: %kernel.root_dir%/cache/%kernel.environment%/swiftmailer.emails

