imports:
    - { resource: config_dev.yml }


framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        enabled: true 

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true
    spool:
        type: file
        path: %kernel.root_dir%/cache/%kernel.environment%/swiftmailer.emails

doctrine:
    dbal:
       host:     192.168.1.44 
       dbname:   jili_test
       password:  MyNewPassword
       charset:  UTF8
