imports:
    - { resource: config_dev.yml }


framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        enabled: false 

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true
    spool:
        type: file
        path: %kernel.root_dir%/cache/%kernel.environment%/swiftmailer.emails

doctrine:
    dbal:
       password:  MyNewPassword
       charset:  UTF8
       host:     192.168.1.12 
       dbname:   jili_test_0721 

monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
            channels: [!user_source]
            
        user_source:
            type: stream
            path: %kernel.logs_dir%/%kernel.environment%.user_source.log
            level: info 
            formatter: monolog.formatter.session_request
            channels: [user_source]
     
        nested:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug
