
parameters:
    offerwow_com.websiteid: 1162  
    offerwow_com.key: "91jili2offerwow"
    offerwow_com.name: "体验广告"
    offerwow_com.category_type: 17 # in ad_category table where cateogry_name ='offerwow' ??
    offerwow_com.task_type: 5


    cpa.category_type:  1 # in table ad_category where category_name='CPA'
    cps.category_type:  1 # in table ad_category where category_name='CPA'
                    
    emar_com.accountid: '458631' # sid uSer id
    emar_com.91jili_com.websiteid: '708089' # wid Website id
    emar_com.91jili_com.key: "91jiLi2emAr3242"
    emar_com.name: "亿玛返利"
    emar_com.cps.category_type: 18 # in ad_category table where cateogry_name ='emar' ??
    emar_com.cps.task_type: 1 

# jili
    emar_com.app_AppKey: '139216929186018017' 
    emar_com.app_AppSecret: 'e7c5367e1ba7d609865389640007df3e'

#    $sdk =array('1326528120671', '4090a94e6c98c2a3c3cf1634cdf29730');
    emar_com.sdk.app_AppKey: '1326528120671'
    emar_com.sdk.app_AppSecret:  '4090a94e6c98c2a3c3cf1634cdf29730'

#    $demo = array('1331544511075406', '1d4abbec4489880adaf9154d948d9be8');
    emar_com.demo.app_AppKey: '1331544511075406'
    emar_com.demo.app_AppSecret: '1d4abbec4489880adaf9154d948d9be8'
#    $jili = array('139216929186018017','e7c5367e1ba7d609865389640007df3e');


    emar_com.page_size: 20 
    emar_com.page_size_of_shoplist: 30 
    emar_com.page_size_of_search: 24 

    emar_com.max_of_total: 1800 

    emar_com.api.orderby_range: [1,2,3] 
    emar_com.api.orderby_default: 1 
    
