parameters:
    database_driver:   pdo_mysql
    database_host:     127.0.0.1
    database_port:     ~
    database_name:     circle_test
    database_user:     ubuntu
    database_password:
    mailer_transport:  smtp
    mailer_host:       smtp.exmail.qq.com
    mailer_user:       account@91jili.com
    mailer_password:   91jili
    mailer_return_path: account@91jili.com

    locale:            zh_CN
    secret:            ThisTokenIsNotSoSecretChangeIt

    91wewen_bind_secret_key_dev: 0b0c2b46e396714623dcd1f4c361918a0658e8131d70e3efc237079a0f26625a   #development

