parameters:
    database_driver:   pdo_mysql
    database_host:     192.168.1.200
    database_port:     ~
    database_name:     jili_db
    database_user:     root
    database_password: ecnavi

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            ThisTokenIsNotSoSecretChangeIt
