parameters:
#### 定义所有的积分类型

### 销售成本    
### 我们有钱赚的部分，比如用户回答问卷后，客户给我们10块钱，我们给用户4块钱，我们赚了6块钱。这里给用户的4块钱就是cost
    # SOP的问卷     
    point_type.cost.survey.sop:      '92'
    # cpa类型的cost
    point_type.cost.cpa.offer99:     '18'
    point_type.cost.cpa.offerwow:    '17'
    # cps 购物返利类型的cost
    point_type.cost.cps.chanet:      '2'
    point_type.cost.cps.emar:        '20'
    point_type.cost.cps.duomai:      '23'
 
### 推广成本
    # 目前包含属性问卷和快速问答
    point_type.expense.vote:         '93'
    # 注册送积分 
    point_type.expense.register:     '32'
    # 用户将积分兑换成现金（支付宝，手机费）的积分类型
    point_type.exchange.alipay:      '11'
    point_type.exchange.mobile_fee:  '12'
    # 长时间不活跃后，积分回收
    point_type.return.expired:       '15'
            
