_homepage:
    path: /
    defaults: { _controller: WenwenFrontendBundle:Home:index }
    schemes:  [http]
    methods:  [GET]

_surveylist:
    path: /surveylist
    defaults: { _controller: WenwenFrontendBundle:Home:surveyList }
    schemes:  [http]
    methods:  [GET]

# offerwow 的数据回传接口
api_offerwow_getinfo:
    path: /api/offerwow/getInfo
    defaults: { _controller: WenwenFrontendBundle:OfferwowRequest:getInfo}
    methods:  [GET, POST]

wenwen_app:
    resource: "@WenwenAppBundle/Controller/"
    type:     annotation
    prefix:   /

wenwen_frontend:
    resource: "@WenwenFrontendBundle/Controller/"
    type:     annotation
    prefix:   /

api:
    resource: "@JiliApiBundle/Controller"
    type: annotation

backend:
    resource: "@JiliBackendBundle/Controller"
    type: annotation

frontend:
    resource: "@JiliFrontendBundle/Controller"
    type: annotation

jili_frontend:
    resource: "@JiliFrontendBundle/Controller/"
    type:     annotation
    prefix:   /

wenwen_frontend:
    resource: "@WenwenFrontendBundle/Controller/"
    type:     annotation

_login:
    path: /login
    defaults: { _controller: WenwenFrontendBundle:User:login}
    schemes:  [https]
    options:
        expose: true

_logout:
    path: /logout
    defaults: { _controller: WenwenFrontendBundle:User:logout}
    schemes:  [http]
    options:
        expose: true

jili_api:
    resource: "@JiliApiBundle/Resources/config/routing.yml"

captcha_routing:
    resource: "@CaptchaBundle/Resources/config/routing.yml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

JMSJobQueueBundle:
    resource: "@JMSJobQueueBundle/Controller/"
    type: annotation
    prefix: /jobs

affiliate_app:
    resource: "@AffiliateAppBundle/Resources/config/routing.yml"
    prefix:   /affiliate

api_v1:
    resource: "@WenwenFrontendBundle/Controller/API/V1"
    type: annotation
    prefix: /api/v1