jili_frontend:
    resource: "@JiliFrontendBundle/Controller/"
    type:     annotation
    prefix:   /
_login:
    path: /login
    defaults: { _controller: JiliApiBundle:User:login}
    schemes:  [https]
    options:
        expose: true

_logout:
    path: /logout
    defaults: { _controller: JiliApiBundle:User:logout}
    schemes:  [http]
    options:
        expose: true

_homepage:
    path: /
    defaults: { _controller: JiliFrontendBundle:Home:index }
    schemes:  [http]
    options:
        expose: true

jili_api:
    resource: "@JiliApiBundle/Resources/config/routing.yml"

jili_emar:
    resource: "@JiliEmarBundle/Resources/config/routing.yml"
    prefix:   /emar

jili_backend:
    resource: "@JiliBackendBundle/Resources/config/routing.yml"
    prefix:   /backend

gregwar_captcha_routing:
    resource: "@GregwarCaptchaBundle/Resources/config/routing/routing.yml"
    prefix: /_gcb

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix: /_internal
