jili_backend:
    resource: "@JiliBackendBundle/Resources/config/routing.yml"
    prefix:   /backend

jili_api:
    resource: "@JiliApiBundle/Resources/config/routing.yml"
gregwar_captcha_routing:
    resource: "@GregwarCaptchaBundle/Resources/config/routing/routing.yml"
    prefix: /_gcb

