parameters:
    database_driver:   pdo_mysql
    database_host:     127.0.0.1
    database_port:     ~
    database_name:     jili_db
    database_user:     root
    database_password: Guobin83

    # 高德地图提供的ip定位API
    amap.ip_locate_api.url: http://restapi.amap.com/v3/ip
    amap.ip_locate_api.key: e44bb2fa5c68147635102e8c50afdcfa

    email.delivery: false

    sendcloud.api_key: Z1OiE2XaNhOGUl5F

    webpower_host: prod-cn-smtp.webpower.asia

    #重要提示：不要以support,admin,postmaster开头，会被webpower列入排除名单而无法正常接受邮件
    webpower_from: cs@91wenwen.net

    webpower_signup_username: 91wenwen-signup
    webpower_signup_password: Na6pK+Uwe7
    webpower_signup_sender: 7-3259@91wenwen-signup.webpower.asia

    webpower_username: 91wenwen
    webpower_password: !rkVQ8jnCp=eH+
    webpower_sender: 26-90032@91wenwen.webpower.asia

    qqmail_host: smtp.exmail.qq.com
    qqmail_username: account@91jili.com
    qqmail_password: D8aspring
    qqmail_sender: %qqmail_username%

    emar_com.cron.AppKey: '139599061334718017'
    emar_com.cron.AppSecret: '98a77033e7a6e8b8533f70eca181d09f'

    cache_enable: false
    cache_lifetime: 3600 #1hour

    sop.admin_host: staff.surveyon.com.dev.researchpanelasia.com
    sop.console_host: console.partners.surveyon.com.dev.researchpanelasia.com
    sop.host: partners.surveyon.com.dev.researchpanelasia.com
    sop.auth.app_id: 27
    sop.auth.app_secret: 1436424899-bd6982201fb7ea024d0926aa1b40d541badf9b4a

    router.request_context.host: www.91jili.com.vag.91jili.com
    router.request_context.scheme: https
    router.request_context.base_url: ~

    signup.crypt_method: blowfish
    signup.salt: dummy

    ssi_project_survey_code:
        api_key: dummy

    #第三方问卷提供商
    gmo_panelCode: 94
    gmo_encryptKey: gB9d280c6fd0C398
    gmo_surveylistUrl: https://st.infopanel.jp/pollon/jp/gmor/research/pollon/enqueteList/facade/EnqueteList.json