parameters:
    database_driver:   pdo_mysql
    database_host:     10.132.35.246
    database_port:     ~
    database_name:     jili_db
    database_user:     root
    database_password: voyage2013jili

    sendcloud.api_key: Z1OiE2XaNhOGUl5F

    webpower_host: prod-cn-smtp.webpower.asia

    webpower_signup_username: 91wenwen-signup
    webpower_signup_password: Na6pK+Uwe7
    webpower_signup_sender: 7-3259@91wenwen-signup.webpower.asia

    webpower_username: 91wenwen
    webpower_password: !rkVQ8jnCp=eH+
    webpower_sender: 26-90032@91wenwen.webpower.asia

    emar_com.cron.AppKey: '139599061334718017'
    emar_com.cron.AppSecret: '98a77033e7a6e8b8533f70eca181d09f'

    cache_enable: true
    cache_lifetime: 28800 #8hours

    sop.admin_host: staff.surveyon.com
    sop.console_host: console.partners.surveyon.com
    sop.host: partners.surveyon.com
    sop.auth.app_id: 56
    sop.auth.app_secret: 1413854247-09f52951f2ad26d916b209bc34b96a6e068aa5a9

    router.request_context.host: www.91wenwen.net
    router.request_context.scheme: https
    router.request_context.base_url: ~

    signup.crypt_method: blowfish
    signup.salt: ★★★★★アジア事業戦略室★★★★★

    ssi_project_survey_code:
        api_key: AFFW0Kkkc1clEdYsowyLcEmm9vluvn