parameters:
    database_driver:   pdo_mysql
    database_host:     127.0.0.1
    database_port:     ~
    database_name:     jili_db
    database_user:     root
    database_password: ecnavi

    sendcloud.api_key: Z1OiE2XaNhOGUl5F

    webpower_host: prod-cn-smtp.webpower.asia

    webpower_signup_username: 91wenwen-signup
    webpower_signup_password: Na6pK+Uwe7
    webpower_signup_sender: 7-3259@91wenwen-signup.webpower.asia

    webpower_username: 91wenwen
    webpower_password: !rkVQ8jnCp=eH+
    webpower_sender: 26-90032@91wenwen.webpower.asia

    emar_com.cron.AppKey: '139599061334718017'
    emar_com.cron.AppSecret: '98a77033e7a6e8b8533f70eca181d09f'