analog-offerwow:
    resource: "@JiliBackendBundle/Controller/AnalogOfferwowController.php"
    type:     annotation

analog-chinanet:
    resource: "@JiliBackendBundle/Controller/AnalogChanetController.php"
    type:     annotation

rebate-activity:
    resource: "@JiliBackendBundle/Controller/RebateActivityController.php"
    type:     annotation

expericnce-advertisement:
    resource: "@JiliBackendBundle/Controller/ExperienceAdvertisementController.php"
    type:     annotation

edm-unsubscribe:
    resource: "@JiliBackendBundle/Controller/EdmUnsubscribeController.php"
    type:     annotation

admin-taobao:
    resource: "@JiliBackendBundle/Controller/AdminTaobaoController.php"
    type:     annotation