
analog-chinanet:
    resource: "@JiliBackendBundle/Controller/AnalogChanetController.php"
    type:     annotation

expericnce-advertisement:
    resource: "@JiliBackendBundle/Controller/ExperienceAdvertisementController.php"
    type:     annotation

edm-unsubscribe:
    resource: "@JiliBackendBundle/Controller/EdmUnsubscribeController.php"
    type:     annotation

admin-taobao:
    resource: "@JiliBackendBundle/Controller/AdminTaobaoController.php"
    type:     annotation
