parameters:
    authentication_ip.action_listener.class: Jili\BackendBundle\EventListener\IpListener

services:
    authentication_ip.action_listener:
        class: %authentication_ip.action_listener.class%
        calls:
            - [setContainer, ["@service_container"] ] 
        arguments: [ [%admin_home_ip%,  %admin_vpn_ip%,  %admin_un_ip% , 127.0.0.1] ]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

