parameters:
    signup.form_handler.class: Jili\FrontendBundle\Form\Handler\SignupHandler

services:
    signup.form_handler:
        class: %signup.form_handler.class%
        calls:
            - [ setLogger, [ @logger ] ] 
            - [ setEntityManager, [ @doctrine.orm.entity_manager ] ] 
            - [ setSession, [ @session ] ] 
            - [ setContainer, [ @service_container ] ] 
            - [ setMailer, [ "@jili_frontend.mailer" ] ]
