parameters:
    campaign_tracking.action_listener.class: Jili\FrontendBundle\EventListener\CampaignTrackingListener

services:
    campaign_tracking.action_listener:
        class: %campaign_tracking.action_listener.class%
        calls:
            - [ setSession, ["@session"] ] 
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
