ALTER TABLE activity_gathering_taobao_order DROP FOREIGN KEY activity_gathering_taobao_order_ibfk_1;
ALTER TABLE point_history00 DROP FOREIGN KEY fk_point_history_00_user;
ALTER TABLE rate_ad_result DROP FOREIGN KEY fk_rate_ad_result_user1;
