-- MySQL Script generated by MySQL Workbench
-- Thu Jan 21 17:34:52 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema jili
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `ssi_respondent`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ssi_respondent` ;

CREATE TABLE IF NOT EXISTS `ssi_respondent` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT(10) UNSIGNED NOT NULL,
  `status_flag` TINYINT(3) UNSIGNED NULL DEFAULT '1',
  `stash_data` TEXT NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `partner_app_member_id_UNIQUE` (`user_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
ROW_FORMAT = COMPRESSED;


-- -----------------------------------------------------
-- Table `ssi_project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ssi_project` ;

CREATE TABLE IF NOT EXISTS `ssi_project` (
  `id` INT UNSIGNED NOT NULL,
  `status_flag` TINYINT(1) UNSIGNED NULL DEFAULT 1,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
ROW_FORMAT = COMPRESSED;


-- -----------------------------------------------------
-- Table `ssi_project_respondent`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ssi_project_respondent` ;

CREATE TABLE IF NOT EXISTS `ssi_project_respondent` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ssi_project_id` INT UNSIGNED NOT NULL,
  `ssi_mail_batch_id` INT NOT NULL,
  `ssi_respondent_id` INT UNSIGNED NOT NULL,
  `start_url_id` VARCHAR(255) NOT NULL,
  `answer_status` TINYINT NOT NULL DEFAULT 1,
  `stash_data` TEXT NULL DEFAULT NULL,
  `completed_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `ssi_project_respondent_uniq` (`ssi_project_id` ASC, `ssi_respondent_id` ASC),
  INDEX `ssi_project_mail_batch_idx` (`ssi_project_id` ASC, `ssi_mail_batch_id` ASC),
  INDEX `ssi_respondent_idx` (`ssi_respondent_id` ASC),
  INDEX `updated_at_answer_status_idx` (`updated_at` ASC, `answer_status` ASC),
  UNIQUE INDEX `ssi_respondent_uniq` (`ssi_project_id` ASC, `ssi_respondent_id` ASC),
  CONSTRAINT `fk_ssi_project_respondent_ssi_project1`
    FOREIGN KEY (`ssi_project_id`)
    REFERENCES `ssi_project` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ssi_project_respondent_ssi_respondent1`
    FOREIGN KEY (`ssi_respondent_id`)
    REFERENCES `ssi_respondent` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
ROW_FORMAT = COMPRESSED;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
