services:
    sop_api.client:
        class: Wenwen\AppBundle\Services\SopHttpfulClient
    ssi_api.conversion_report_iterator:
        class: Wenwen\AppBundle\Services\SsiConversionReportIterator
    monolog.logger.sop_notification:
        class: Wenwen\AppBundle\Services\Logger\SopNotificationLogger
        arguments: ["@logger"]
        tags:
            - { name: monolog.logger, channel: sop_notification }
    monolog.logger.ssi_notification:
        class: Wenwen\AppBundle\Services\Logger\SsiNotificationLogger
        arguments: ["@logger"]
        tags:
            - { name: monolog.logger, channel: ssi_notification }
    monolog.logger.email_delivery:
        class: Wenwen\AppBundle\Services\Logger\EmailDeliveryLogger
        arguments: ["@logger"]
        tags:
            - { name: monolog.logger, channel: email_delivery }
    monolog.logger.fake_answer:
        class: Wenwen\AppBundle\Services\Logger\FakeAnswerLogger
        arguments: ["@logger"]
        tags:
            - { name: monolog.logger, channel: fake_answer }
    monolog.logger.bot_registration:
        class: Wenwen\AppBundle\Services\Logger\FakeAnswerLogger
        arguments: ["@logger"]
        tags:
            - { name: monolog.logger, channel: bot_registration }
