CREATE TABLE `recruit_offer99` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL,
  `tid` varchar(32) NOT NULL COMMENT 'the tid passed by ad-platform , identity of user in ad-platform side',
  `uid` varchar(128) DEFAULT NULL COMMENT 'panelist identity, hash value, generated by 91ww ',
  `is_valid` smallint(4) DEFAULT NULL COMMENT '0: valid signup, 1: invalid signup',
  `invalid_reason` varchar(255) DEFAULT NULL COMMENT 'invalid reason json encoded string',
  `updated_at` datetime DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `user_id` (`user_id`),
  UNIQUE KEY `tid` (`tid`),
  KEY `created_at` (`created_at`),
  KEY `uid` (`uid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
