
check_log=/data/91jili/merge/log/check_result.log
check_log_bk=/data/91jili/merge/log/check_result_`date +%Y%m%d-%H`.log

time_fmt=real\t%E\nuser\t%U\nsys\t%S\n
merge_dir=/data/91jili/merge

check-user-password:
	echo 'start checking...' > ${check_log} 
	/usr/bin/time -ao ${check_log}  -f "${time_fmt}" php -f  user_merged_password.php  1>>${check_log}  2>&1
	grep -h real  ${check_log}   | cut -b 5-100 | awk -F '[m|:|s]' 'BEGIN{m=0;s=0;} { m=m+$$1;s=s+$$2; } END{ print  (m + int(s/60)) "m" (s % 60) "s"}' 
	cp ${check_log}  ${check_log_bk}
	echo 'completed' >> ${check_log} 

	
.SILENT:


