mail:
    to:    admin@voyagegroup.com.cn,xujf@voyagegroup.com.cn
interface:
    balance:    1000
    url:    http://59.83.33.14/custom_balanceV1.php
    custom_sn:    B772AA94ABDC6BEE
    prv_key:    5E703068E764D3DC