<?php

namespace Wenwen\FrontendBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SurveyListJobRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SurveyListJobRepository extends EntityRepository
{
    public function getSurveyListJob($userId, $min, $max)
    {
        $qb = $this->createQueryBuilder('t');
        $qb->where('t.userId = :userId');
        $qb->andWhere('t.createdAt between :min and :max');
        $qb->setParameter('userId', $userId);
        $qb->setParameter('min', $min);
        $qb->setParameter('max', $max);
        return $qb->getQuery()->getOneOrNullResult();
    }
}
