parameters:
    emar_api.logger.class: Jili\EmarBundle\EventListener\Logger
    emar_api.callback_processor.class: Jili\EmarBundle\EventListener\CallbackProcessor
    emar_api.callback_validation.class:  Jili\EmarBundle\EventListener\CallbackValidation

    emar_request.connection.class: Jili\EmarBundle\EventListener\EmarRequestConnection
# hot activity
    hotactivity.category_get.class:  Jili\EmarBundle\EventListener\HotactivityCategoryGetRequest
    hotactivity.website_get.class:  Jili\EmarBundle\EventListener\HotactivityWebsiteGetRequest
    hotactivity.list_get.class: Jili\EmarBundle\EventListener\HotactivityListGetRequest

# ghs
    ghs.category_get.class:  Jili\EmarBundle\EventListener\GhsCategoryGetRequest


# product/general
    general.category_get.class:  Jili\EmarBundle\EventListener\ProductCategoryGetRequest
# product
    product.list_get.class: Jili\EmarBundle\EventListener\ProductListGetRequest
    product.search.class: Jili\EmarBundle\EventListener\ProductSearch
    product.filters.class: Jili\EmarBundle\EventListener\ProductFilters

# website
    website.category_get.class:  Jili\EmarBundle\EventListener\WebsiteCategoryGetRequest
    website.list_get.class:  Jili\EmarBundle\EventListener\WebsiteListGetRequest
    website.detail_get.class:  Jili\EmarBundle\EventListener\WebsiteDetailGetRequest
    website.search.class:  Jili\EmarBundle\EventListener\WebsiteSearch


services:
    emar_api.logger:
        class: %emar_api.logger.class%
        arguments: [ @logger, @doctrine.orm.entity_manager ]

    emar_api.callback_validation:
        class: %emar_api.callback_validation.class%
        arguments: [ @logger,@doctrine.orm.entity_manager ]
        calls:
            - [setConfig, [%emar%] ] 
            - [setContainer, [@service_container] ] 

#    emar_api.callback_processor:
#    class: %emar_api.callback_processor.class%

    emar_api.callback_processor:
        class: %emar_api.callback_processor.class%
        arguments: [ @logger,@doctrine.orm.entity_manager ]
        calls:
            - [setContainer, [@service_container] ] 
            - [setTaskLogger, [@general_api.task_history] ]
            - [setPointLogger, [@general_api.point_history] ]
            - [setRebatePointCaculator, [@rebate_point.caculator] ]
            - [setConfig, [%emar%] ] 

    emar_request.connection:
       class: %emar_request.connection.class%
       arguments: [ %emar_com.app_AppKey%, %emar_com.app_AppSecret% ]
       calls:
            - [setLogger, [ @logger ] ] 

#    jili_emar.example:
#        class: %jili_emar.example.class%
#        arguments: [@service_id, plain_value, %parameter%]

    hotactivity.category_get:
        class: %hotactivity.category_get.class%
        calls:
            - [ setConnection,[ @emar_request.connection ] ]
            - [ setLogger, [ @logger ] ] 

    hotactivity.website_get:
        class: %hotactivity.website_get.class%
        calls:
            - [ setConnection,[ @emar_request.connection ] ]
            - [ setLogger, [ @logger ] ] 

    hotactivity.list_get:
        class: %hotactivity.list_get.class%
        calls:
            - [ setConnection,[ @emar_request.connection ] ]
            - [ setLogger, [ @logger ] ] 
            - [ setPageSize, [ %emar_com.page_size% ] ] 

    ghs.category_get:
        class: %ghs.category_get.class%
        calls:
            - [ setConnection,[ @emar_request.connection ] ]
            - [ setLogger, [ @logger ] ] 


    general.category_get:
        class: %general.category_get.class%
        calls:
            - [ setConnection,[ @emar_request.connection ] ]
            - [ setLogger, [ @logger ] ] 

#    general.website_get:
#        class: %general.website_get.class%
#        calls:
#            - [ setConnection,[ @emar_request.connection ] ]
#            - [ setLogger, [ @logger ] ] 
#
    website.category_get:
        class: %website.category_get.class%
        calls:
            - [ setConnection,[ @emar_request.connection ] ]
            - [ setLogger, [ @logger ] ] 

    website.list_get:
        class: %website.list_get.class%
        calls:
            - [ setConnection,[ @emar_request.connection ] ]
            - [ setLogger, [ @logger ] ] 

    website.detail_get:
        class: %website.detail_get.class%
        calls:
            - [ setConnection, [ @emar_request.connection ] ]
            - [ setLogger, [ @logger ] ] 

    website.search:
        class: %website.search.class%
        calls:
            - [ setLogger, [ @logger ] ] 
            - [ setListGet , [ @website.list_get ] ]
            - [ setDetailGet , [ @website.detail_get ] ]

    product.list_get:
        class: %product.list_get.class%
        calls:
            - [ setConnection,[ @emar_request.connection ] ]
            - [ setLogger, [ @logger ] ] 
            - [ setPageSize, [ %emar_com.page_size% ] ] 

    product.search:
        class: %product.search.class%
        calls:
            - [ setConnection,[ @emar_request.connection ] ]
            - [ setLogger, [ @logger ] ] 
            - [ setPageSize, [ %emar_com.page_size% ] ] 

    product.filters:
        class: %product.filters.class%
        calls:
            - [ setLogger, [ @logger ] ] 
            - [ setGeneralCategoryGet, [ @general.category_get ] ] 
            - [ setWebsiteCategoryGet, [ @website.category_get ] ] 
            - [ setWebsiteListGet, [ @website.list_get ] ] 

