parameters:
    emar_api.logger.class: Jili\EmarBundle\EventListener\Logger
    emar_api.callback_processor.class: Jili\EmarBundle\EventListener\CallbackProcessor
    emar_api.callback_validation.class:  Jili\EmarBundle\EventListener\CallbackValidation

services:
    emar_api.logger:
        class: %emar_api.logger.class%
        arguments: [ "@logger","@doctrine.orm.entity_manager" ]

    emar_api.callback_validation:
        class: %emar_api.callback_validation.class%
        arguments: [ "@logger","@doctrine.orm.entity_manager" ]
        calls:
            - [setConfig, [%emar%] ] 
            - [setContainer, ["@service_container"] ] 

#    emar_api.callback_processor:
#        class: %emar_api.callback_processor.class%

    emar_api.callback_processor:
        class: %emar_api.callback_processor.class%
        arguments: [ "@logger","@doctrine.orm.entity_manager" ]
        calls:
            - [setContainer, ["@service_container"] ] 
            - [setTaskLogger, ["@general_api.task_history"] ]
            - [setPointLogger, ["@general_api.point_history"] ]
            - [setRebatePointCaculator, ["@rebate_point.caculator"] ]
            - [setConfig, [%emar%] ] 
#    jili_emar.example:
#        class: %jili_emar.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
