
parameters:
    offerwow_com: 
        validations:
            1: { errorno: "offerwow-01", message: "出现空参数"}
            2: { errorno: "offerwow-02", message: "网站id不存在" }
            3: { errorno: "offerwow-03", message: "uid会员不存在" }
            4: { errorno: "offerwow-04", message: "已发放奖励的Eventid重复" }
            5: { errorno: "offerwow-05", message: "immediate=0" } #
            6: { errorno: "offerwow-06", message: "immediate=1" } # instant order request cannt overwrite the pendings order record
            sign: { errorno: "signature error", message: "签名验证出错" }

        #sign=md5(memberId+point+eventId+websiteId+immediate+key)

        key: "%offerwow_com.key%"
        websiteid: %offerwow_com.websiteid%  
        name: "%offerwow_com.name%"
        category_type: %offerwow_com.category_type% # in ad_category table where cateogry_name ='offerwow' ??
        task_type: %offerwow_com.task_type% 

        immediate_status:
           HANGUP_SUSPEND: 0 # ：非即时返利活动,处于待审核状态；
           INSTANT_PASSED: 1 #：即时返利活动，需发放奖励给会员；
           HANGUP_PASSED: 2 #：非即时返利活动，审核通过，重新回传，发放奖励给会员；
           HANGUP_REFUSED: 3 #：非即时返利活动，审核不通过，重新回传，不发放奖励；

