default:
    resource: "@JiliApiBundle/Controller/DefaultController.php"
    prefix:   /
    type:     annotation
user:
    resource: "@JiliApiBundle/Controller/UserController.php"
    prefix:   /user
    type:     annotation   
advertiserment:
    resource: "@JiliApiBundle/Controller/AdvertisermentController.php"
    prefix:   /advertiserment
    type:     annotation
callboard:
    resource: "@JiliApiBundle/Controller/CallboardController.php"
    prefix:   /callboard
    type:     annotation
exchange:
    resource: "@JiliApiBundle/Controller/ExchangeController.php"
    prefix:   /exchange
    type:     annotation
api:
    resource: "@JiliApiBundle/Controller/ApiController.php"
    prefix:   /api
    type:     annotation
admin:
    resource: "@JiliApiBundle/Controller/AdminController.php"
    prefix:   /admin
    type:     annotation