
advertiserment:
    resource: "@JiliApiBundle/Controller/AdvertisermentController.php"
    prefix:   /advertiserment
    type:     annotation

callboard:
    resource: "@JiliApiBundle/Controller/CallboardController.php"
    prefix:   /callboard
    type:     annotation

exchange:
    resource: "@JiliApiBundle/Controller/ExchangeController.php"
    prefix:   /exchange
    type:     annotation

admin:
    resource: "@JiliApiBundle/Controller/AdminController.php"
    prefix:   /admin
    type:     annotation

marketActivity:
    resource: "@JiliApiBundle/Controller/MarketActivityController.php"
    prefix:   /marketActivity
    type:     annotation

api-offer99:
    resource: "@JiliApiBundle/Controller/Offer99Controller.php"
    type:     annotation
    prefix:   /

top:
    resource: "@JiliApiBundle/Controller/TopController.php"
    type:     annotation
    prefix:   /
