post:
    resource: "@JiliApiBundle/Controller/DefaultController.php"
    type:     annotation
user:
    resource: "@JiliApiBundle/Controller/UserController.php"
    prefix:   /user
    type:     annotation   
advertiserment:
    resource: "@JiliApiBundle/Controller/AdvertisermentController.php"
    prefix:   /advertiserment
    type:     annotation