ActionType:
    type: entity
    table: action_type
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        actionType:
            type: string
            length: 45
            fixed: false
            nullable: true
            column: action_type
    lifecycleCallbacks: {  }
