AdPosition:
    type: entity
    table: ad_position
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        type:
            type: string
            length: 45
            fixed: false
            nullable: true
        position:
            type: integer
            unsigned: false
            nullable: true
        adId:
            type: integer
            unsigned: false
            nullable: false
            column: ad_id
    lifecycleCallbacks: {  }
