Advertiserment:
    type: entity
    table: advertiserment
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        type:
            type: integer
            unsigned: false
            nullable: false
        showFlag:
            type: integer
            unsigned: false
            nullable: false
            column: show_flag
        title:
            type: string
            length: 45
            fixed: false
            nullable: true
        createdTime:
            type: datetime
            nullable: true
            column: created_time
        startTime:
            type: datetime
            nullable: true
            column: start_time
        endTime:
            type: datetime
            nullable: true
            column: end_time
        updateTime:
            type: datetime
            nullable: true
            column: update_time
        content:
            type: string
            length: 10000
            fixed: false
            nullable: true
        imageurl:
            type: string
            length: 45
            fixed: false
            nullable: true
        incentiveType:
            type: string
            length: 45
            fixed: false
            nullable: true
            column: 'incentive _type'
        info:
            type: string
            length: 45
            fixed: false
            nullable: true
        income:
            type: string
            length: 45
            fixed: false
            nullable: true
        category:
            type: integer
            unsigned: false
            nullable: false
        deleteFlag:
            type: integer
            unsigned: false
            nullable: true
            column: delete_flag
    lifecycleCallbacks: {  }
