BlackUsers:
    type: entity
    table: black_users
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        userId:
            type: integer
            unsigned: false
            nullable: false
            column: user_id
        blackedDate:
            type: datetime
            nullable: true
            column: blacked_date
        status:
            type: integer
            unsigned: false
            nullable: true
    lifecycleCallbacks: {  }
