Callboard:
    type: entity
    table: callboard
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        title:
            type: string
            length: 45
            fixed: false
            nullable: true
        content:
            type: string
            length: 45
            fixed: false
            nullable: true
        startTime:
            type: datetime
            nullable: true
            column: start_time
        endTime:
            type: datetime
            nullable: true
            column: end_time
        url:
            type: string
            length: 45
            fixed: false
            nullable: true
    lifecycleCallbacks: {  }
