LoginLog:
    type: entity
    table: login_log
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        userId:
            type: integer
            unsigned: false
            nullable: false
            column: user_id
        loginDate:
            type: datetime
            nullable: true
            column: login_date
        loginIp:
            type: string
            length: 45
            fixed: false
            nullable: true
            column: login_ip
    lifecycleCallbacks: {  }
