RateAd:
    type: entity
    table: rate_ad
    fields:
        adId:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: ad_id
            generator:
                strategy: IDENTITY
        incentiveRate:
            type: string
            length: 45
            fixed: false
            nullable: true
            column: incentive_rate
    lifecycleCallbacks: {  }
