RateAdResult:
    type: entity
    table: rate_ad_result
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        userId:
            type: integer
            unsigned: false
            nullable: false
            column: user_id
        rateAdId:
            type: integer
            unsigned: false
            nullable: false
            column: rate_ad_id
        resultPoint:
            type: string
            length: 45
            fixed: false
            nullable: true
            column: result_point
    lifecycleCallbacks: {  }
